### ISSUE TITLE
First issue still not resolved coz the fix is invalid

### ISSUE THREAD

**Issue by GoodBoiDoggo** [thereserayza/order-service#3]
The two links are still similar:
TAKE NOTE: The server cant identify whether a part of the url is a variable or not. As a result, the two paths below are still the same. (the string "user" can be interpreted as a {customerId})
```java
@GetMapping("/user/{customerId}")
	public List<Order> findByCustomerId(@PathVariable String customerId) {
		Query query = new Query().addCriteria(Criteria.where("customerId").is(customerId));
		return mongoTemplate.find(query, Order.class, "order");
	}
	
	@GetMapping("/{customerId}/{orderDate}")
	public List<Order> findByCustomerIdAndOrderDate(@PathVariable String customerId, 
			@PathVariable @DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate date) {
		Query query = new Query().addCriteria(Criteria.where("customerId").is(customerId).and("orderDate").gte(date));
		return mongoTemplate.find(query, Order.class, "order");
	}
```

**Comment by thereserayza** [comment]
I don't get how you reached that point because I stated in the parameters in the second method that the two are pathvariables.

**Comment by GoodBoiDoggo** [comment]
exactly my point if u think like that, youll encounter these kind of errors a lot.

**Comment by GoodBoiDoggo** [comment]
if the front end sends the link. "/user/1234234"
Both of the mappings above will match it

**Comment by thereserayza** [comment]
I checked the code and they both work differently so there should be nothing wrong with the two methods.
